---
## 1. Warm-Up y Repaso de U5_02 <a id='1-warmup'></a>

In [1]:
# ============================================================
# WARM-UP: Entorno y Dependencias — U5_03
# ============================================================
import subprocess, sys, os
from pathlib import Path

def check_install(package, import_name=None):
    name = import_name or package.split('==')[0].replace('-', '_')
    try:
        __import__(name)
        print(f"  OK: {package}")
    except ImportError:
        print(f"  Instalando {package}...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package, "-q"])
        print(f"  Instalado: {package}")

packages = [
    ("crewai==0.80.0",                   "crewai"),
    ("crewai-tools==0.14.0",             "crewai_tools"),
    ("langchain-openai==0.3.12",         "langchain_openai"),
    ("langchain-google-genai==2.1.4",    "langchain_google_genai"),
    ("python-dotenv==1.1.0",             "dotenv"),
]

print("Verificando paquetes...")
for pkg, imp in packages:
    check_install(pkg, imp)

# Fijar openai a versión compatible con langchain_openai 0.3.12
# openai >= 1.79 introdujo resources/videos.py con un bug que rompe ChatOpenAI
import openai as _oai
_ver = tuple(int(x) for x in _oai.__version__.split(".")[:2])
if _ver >= (1, 79):
    print(f"  [!] openai {_oai.__version__} incompatible con langchain_openai 0.3.12")
    print("      Reinstalando versión compatible (esto puede tardar 10-20s)...")
    subprocess.check_call([
        sys.executable, "-m", "pip", "install",
        "openai>=1.58.0,<1.79.0", "--force-reinstall", "-q"
    ])
    print("  openai reinstalado correctamente.")
    print()
    print("  *** IMPORTANTE: REINICIA el kernel ahora ***")
    print("  Menú → Kernel → Restart Kernel, luego vuelve a ejecutar desde la celda 1")
    raise SystemExit("Reinicia el kernel: Kernel > Restart Kernel and Run All Cells")
else:
    print(f"  OK: openai {_oai.__version__}")

from dotenv import load_dotenv
load_dotenv(override=True)

# project root
project_root = Path.cwd()
for _ in range(5):
    if (project_root / "external_skills").exists():
        break
    project_root = project_root.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# Detectar backends disponibles
google_key     = os.environ.get("GOOGLE_API_KEY")
openrouter_key = os.environ.get("OPENROUTER_API_KEY")

backend = (
    "OpenRouter"     if openrouter_key else
    "Gemini"         if google_key     else
    "Sin backend — configura OPENROUTER_API_KEY o GOOGLE_API_KEY en .env"
)

print(f"\nProject root: {project_root}")
print(f"Backend LLM activo: {backend}")
print("Warm-up completado.")


Verificando paquetes...


  OK: crewai==0.80.0


  OK: crewai-tools==0.14.0


  OK: langchain-openai==0.3.12


  OK: langchain-google-genai==2.1.4
  OK: python-dotenv==1.1.0
  OK: openai 1.78.1

Project root: C:\IA Nanotecnología\Antigravity-Nano-Research-Multiagentic-Core-main
Backend LLM activo: OpenRouter
Warm-up completado.


---
## Ejercicio de Extensión: Plan de Negocio — Clasificador SEM como Servicio

Construimos una **crew de 4 agentes** para producir un plan de negocio sobre la comercialización
del clasificador de micrografías SEM (ResNet-18) como servicio SaaS para laboratorios de nanotecnología.

| # | Agente | Rol | Función |
|---|--------|-----|---------|
| 1 | **Científico** | Viabilidad técnica | Valida que el modelo (99.07% accuracy) es competitivo y define limitaciones |
| 2 | **Economista** | Análisis de mercado | Estima TAM, pricing y costos operativos |
| 3 | **Regulatorio** | Aspectos legales | Analiza normativa de nanomateriales y requisitos de certificación |
| 4 | **Redactor Ejecutivo** | Integración | Produce un executive summary de 1 página |

Al final, evaluamos con `output_scorer` usando criterios de dominio de negocio.

In [2]:
# ============================================================
# EJERCICIO: CREW DE 4 AGENTES — PLAN DE NEGOCIO SEM
# ============================================================
import os, logging
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, Process, LLM
from crewai.tools import BaseTool

logging.getLogger("litellm").setLevel(logging.ERROR)
load_dotenv(override=True)

openrouter_key = os.getenv("OPENROUTER_API_KEY")
if not openrouter_key:
    raise ValueError("OPENROUTER_API_KEY no encontrada en .env")

# --- Tool: Métricas del Modelo SEM ---
class SEMModelMetricsTool(BaseTool):
    name: str = "sem_model_metrics"
    description: str = (
        "Obtiene las metricas de rendimiento del clasificador SEM ResNet-18. "
        "Usa esta tool para validar la viabilidad tecnica del producto."
    )
    def _run(self, query: str = "") -> str:
        return (
            "Metricas del Clasificador SEM ResNet-18:\n"
            "- Accuracy: 99.07% (106/107 correctas)\n"
            "- F1-Score: 0.9903\n"
            "- AUC-ROC: 0.9943\n"
            "- Clases: Nanoparticles (0D) vs Nanowires (1D)\n"
            "- Dataset: NFFA-EUROPE SEM (535 imagenes)\n"
            "- Arquitectura: ResNet-18 fine-tuned desde ImageNet\n"
            "- Interpretabilidad: Grad-CAM en layer4[-1]\n"
            "- Tiempo de inferencia: ~50ms por imagen (GPU)\n"
            "- Error: 1/107 (una nanoparticula clasificada como nanohilo)"
        )

sem_metrics_tool = SEMModelMetricsTool()
print("Tool SEM Metrics definida.")
print(sem_metrics_tool._run())

Tool SEM Metrics definida.
Metricas del Clasificador SEM ResNet-18:
- Accuracy: 99.07% (106/107 correctas)
- F1-Score: 0.9903
- AUC-ROC: 0.9943
- Clases: Nanoparticles (0D) vs Nanowires (1D)
- Dataset: NFFA-EUROPE SEM (535 imagenes)
- Arquitectura: ResNet-18 fine-tuned desde ImageNet
- Interpretabilidad: Grad-CAM en layer4[-1]
- Tiempo de inferencia: ~50ms por imagen (GPU)
- Error: 1/107 (una nanoparticula clasificada como nanohilo)


In [3]:
# ============================================================
# DEFINICIÓN DE LOS 4 AGENTES
# ============================================================

MODELS_FALLBACK = [
    "google/gemini-2.5-flash",
    "openai/gpt-4o-mini",
    "anthropic/claude-3-haiku",
]

def crear_llm(temperature=0.3, max_tokens=3000):
    for model_id in MODELS_FALLBACK:
        try:
            _c = LLM(
                model=f"openrouter/{model_id}",
                api_key=openrouter_key,
                temperature=temperature,
                max_tokens=max_tokens,
            )
            _c.call([{"role": "user", "content": "OK"}])
            return _c, model_id
        except Exception:
            continue
    raise RuntimeError("No hay modelos disponibles")

llm_obj, model_name = crear_llm(temperature=0.2)
print(f"LLM: {model_name}")

# --- AGENTE 1: CIENTÍFICO ---
cientifico = Agent(
    role="Cientifico Senior en Vision Artificial y Nanomateriales",
    goal=(
        "Evaluar la viabilidad tecnica del clasificador SEM ResNet-18 como producto "
        "comercial, identificando fortalezas, limitaciones y mejoras necesarias."
    ),
    backstory=(
        "Eres un investigador con 12 anos de experiencia en computer vision aplicada a "
        "microscopia electronica. Has desarrollado modelos de clasificacion para TEM, SEM y AFM "
        "en laboratorios de materiales avanzados. Conoces el estado del arte en transfer learning "
        "para imagenes cientificas y puedes evaluar si un modelo es competitivo frente a alternativas "
        "comerciales como Thermo Fisher Avizo o MIPAR. Siempre cuantificas tus argumentos con metricas."
    ),
    llm=llm_obj,
    tools=[sem_metrics_tool],
    verbose=True,
    max_iter=3,
    memory=False,
    allow_delegation=False,
)

# --- AGENTE 2: ECONOMISTA ---
economista = Agent(
    role="Analista de Mercado en Tecnologia Deep Tech",
    goal=(
        "Realizar un analisis de mercado para un servicio SaaS de clasificacion "
        "automatica de micrografias SEM, incluyendo TAM, pricing y proyecciones."
    ),
    backstory=(
        "Eres analista senior en un fondo de venture capital especializado en deep tech y "
        "materiales avanzados. Has evaluado mas de 50 startups en nanotecnologia y conoces "
        "el mercado de software de caracterizacion de materiales (Thermo Fisher, Bruker, ZEISS). "
        "Tu analisis siempre incluye TAM/SAM/SOM, modelo de pricing y unit economics. "
        "Usas datos de mercado reales cuando estan disponibles y estimaciones conservadoras cuando no."
    ),
    llm=llm_obj,
    verbose=True,
    max_iter=3,
    memory=False,
    allow_delegation=False,
)

# --- AGENTE 3: REGULATORIO ---
regulatorio = Agent(
    role="Especialista en Regulacion de Nanotecnologia y Software Medico",
    goal=(
        "Analizar los requisitos legales y normativos para comercializar un software de "
        "clasificacion de nanomateriales, incluyendo certificaciones y compliance."
    ),
    backstory=(
        "Eres abogado con especializacion en regulacion de nanotecnologia y dispositivos de "
        "software cientifico. Conoces la normativa REACH (EU), TSCA (US), y las guias de la "
        "OECD para nanomateriales. Has asesorado a 20+ empresas en el proceso de certificacion "
        "de software analitico para laboratorios (ISO 17025, 21 CFR Part 11). "
        "Tu analisis siempre distingue entre requisitos obligatorios y recomendados por jurisdiccion."
    ),
    llm=llm_obj,
    verbose=True,
    max_iter=3,
    memory=False,
    allow_delegation=False,
)

# --- AGENTE 4: REDACTOR EJECUTIVO ---
redactor_ejecutivo = Agent(
    role="Redactor de Executive Summaries para Inversores",
    goal=(
        "Integrar los analisis tecnico, economico y regulatorio en un executive summary "
        "de 1 pagina que convenza a inversores de la oportunidad de negocio."
    ),
    backstory=(
        "Eres un ex-consultor de McKinsey especializado en deep tech que ahora redacta "
        "pitch decks y executive summaries para startups de nanotecnologia. Tu estilo es "
        "conciso, orientado a datos y enfocado en el retorno de inversion. Cada seccion tiene "
        "maximo 3-4 oraciones. Siempre incluyes: Problema, Solucion, Mercado, Modelo de Negocio, "
        "Equipo/Tecnologia y Ask (cuanto se necesita invertir y para que)."
    ),
    llm=llm_obj,
    verbose=True,
    max_iter=3,
    memory=False,
    allow_delegation=False,
)

print("\n4 agentes configurados:")
for a in [cientifico, economista, regulatorio, redactor_ejecutivo]:
    print(f"  - {a.role}")

LLM: google/gemini-2.5-flash

4 agentes configurados:
  - Cientifico Senior en Vision Artificial y Nanomateriales
  - Analista de Mercado en Tecnologia Deep Tech
  - Especialista en Regulacion de Nanotecnologia y Software Medico
  - Redactor de Executive Summaries para Inversores


In [4]:
# ============================================================
# DEFINICIÓN DE TASKS CON DEPENDENCIAS
# ============================================================

tarea_cientifico = Task(
    description=(
        "Evalua la viabilidad tecnica del clasificador SEM ResNet-18 como producto comercial. "
        "Usa la tool sem_model_metrics para obtener las metricas reales del modelo. "
        "Analiza: (1) Competitividad frente a soluciones existentes, "
        "(2) Limitaciones tecnicas y como mitigarlas, "
        "(3) Roadmap de mejoras (multi-clase, segmentacion, etc.), "
        "(4) Requisitos de infraestructura (GPU, cloud)."
    ),
    expected_output=(
        "Informe tecnico de 200-300 palabras con metricas cuantitativas, "
        "comparacion con al menos 2 alternativas comerciales, "
        "y un roadmap de 3 fases de mejora del producto."
    ),
    agent=cientifico,
)

tarea_economista = Task(
    description=(
        "Realiza un analisis de mercado para un SaaS de clasificacion automatica de "
        "micrografias SEM. Incluye: (1) TAM del mercado de software de caracterizacion "
        "de materiales, (2) Segmento objetivo (universidades, centros de I+D, industria), "
        "(3) Modelo de pricing (por imagen, suscripcion mensual, enterprise), "
        "(4) Estimacion de costos operativos (cloud GPU, desarrollo, soporte)."
    ),
    expected_output=(
        "Analisis de mercado de 200-300 palabras con cifras de TAM/SAM/SOM, "
        "tabla de pricing con 3 tiers, y proyeccion de ingresos a 3 anos."
    ),
    agent=economista,
    context=[tarea_cientifico],
)

tarea_regulatorio = Task(
    description=(
        "Analiza los requisitos legales para comercializar un software de clasificacion "
        "de nanomateriales a nivel global. Cubre: (1) Regulacion de nanomateriales (REACH, TSCA), "
        "(2) Certificaciones de software analitico (ISO 17025), "
        "(3) Proteccion de datos y propiedad intelectual, "
        "(4) Diferencias entre mercados US, EU y Asia."
    ),
    expected_output=(
        "Analisis regulatorio de 200-300 palabras con tabla de requisitos por jurisdiccion, "
        "timeline estimado de certificacion y costos asociados."
    ),
    agent=regulatorio,
    context=[tarea_cientifico],
)

tarea_executive_summary = Task(
    description=(
        "Integra los informes del cientifico, economista y regulatorio en un "
        "executive summary de exactamente 1 pagina (400-500 palabras) para inversores. "
        "Estructura: Problema → Solucion → Mercado → Modelo de Negocio → "
        "Tecnologia → Regulatorio → Ask (inversion necesaria)."
    ),
    expected_output=(
        "Executive summary de 1 pagina en formato Markdown con 7 secciones, "
        "cada una de maximo 3-4 oraciones, con datos cuantitativos de los informes previos."
    ),
    agent=redactor_ejecutivo,
    context=[tarea_cientifico, tarea_economista, tarea_regulatorio],
)

print("4 tasks definidas con dependencias:")
print("  tarea_cientifico → tarea_economista")
print("  tarea_cientifico → tarea_regulatorio")
print("  [cientifico + economista + regulatorio] → tarea_executive_summary")

4 tasks definidas con dependencias:
  tarea_cientifico → tarea_economista
  tarea_cientifico → tarea_regulatorio
  [cientifico + economista + regulatorio] → tarea_executive_summary


In [5]:
# ============================================================
# CREAR Y EJECUTAR LA CREW
# ============================================================

crew_negocio = Crew(
    agents=[cientifico, economista, regulatorio, redactor_ejecutivo],
    tasks=[tarea_cientifico, tarea_economista, tarea_regulatorio, tarea_executive_summary],
    process=Process.sequential,
    verbose=True,
)

print("Crew configurada: 4 agentes, 4 tasks, proceso secuencial")
print("Ejecutando plan de negocio...")
print("=" * 60)

resultado_negocio = crew_negocio.kickoff()

print("\n" + "=" * 60)
print("EXECUTIVE SUMMARY FINAL:")
print("=" * 60)
print(resultado_negocio.raw)

Crew configurada: 4 agentes, 4 tasks, proceso secuencial
Ejecutando plan de negocio...


╭──────────────────────────────────────────── ✨ Update Available ✨ ─────────────────────────────────────────────╮
│                                                                                                                 │
│  A new version of CrewAI is available!                                                                          │
│                                                                                                                 │
│  Current version: 1.11.0                                                                                        │
│  Latest version:  1.14.4                                                                                        │
│                                                                                                                 │
│  To update, run: uv sync --upgrade-package crewai                                                               │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────── 🚀 Crew Execution Started ───────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Started                                                                                         │
│  Name: crew                                                                                                     │
│  ID: c43cd0dd-ee4b-4e67-b42e-be27af1b89da                                                                       │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── 📋 Task Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Started                                                                                                   │
│  Name: Evalua la viabilidad tecnica del clasificador SEM ResNet-18 como producto comercial. Usa la tool         │
│  sem_model_metrics para obtener las metricas reales del modelo. Analiza: (1) Competitividad frente a            │
│  soluciones existentes, (2) Limitaciones tecnicas y como mitigarlas, (3) Roadmap de mejoras (multi-clase,       │
│  segmentacion, etc.), (4) Requisitos de infraestructura (GPU, cloud).                                           │
│  ID: 58af50f7-a2c5-4bf7-9854-a04631a85916                                                                       │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Cientifico Senior en Vision Artificial y Nanomateriales                                                 │
│                                                                                                                 │
│  Task: Evalua la viabilidad tecnica del clasificador SEM ResNet-18 como producto comercial. Usa la tool         │
│  sem_model_metrics para obtener las metricas reales del modelo. Analiza: (1) Competitividad frente a            │
│  soluciones existentes, (2) Limitaciones tecnicas y como mitigarlas, (3) Roadmap de mejoras (multi-clase,       │
│  segmentacion, etc.), (4) Requisitos de infraestructura (GPU, cloud).                                           │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Tool sem_model_metrics executed with result: Metricas del Clasificador SEM ResNet-18:
- Accuracy: 99.07% (106/107 correctas)
- F1-Score: 0.9903
- AUC-ROC: 0.9943
- Clases: Nanoparticles (0D) vs Nanowires (1D)
- Dataset: NFFA-EUROPE SEM (535 imag...


╭──────────────────────────────────────── 🔧 Tool Execution Started (#1) ─────────────────────────────────────────╮
│                                                                                                                 │
│  Tool: sem_model_metrics                                                                                        │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────── ✅ Tool Execution Completed (#1) ────────────────────────────────────────╮
│                                                                                                                 │
│  Tool Completed                                                                                                 │
│  Tool: sem_model_metrics                                                                                        │
│  Output: Metricas del Clasificador SEM ResNet-18:                                                               │
│  - Accuracy: 99.07% (106/107 correctas)                                                                         │
│  - F1-Score: 0.9903                                                                                             │
│  - AUC-ROC: 0.9943                                                                                              │
│  - Clases: Nanoparticles (0D) vs Nanowires (1D)                                                                 │
│  - Dataset: NFFA-EUROPE SEM (535 imagenes)                                                                      │
│  - Arquitectura: ResNet-18 fine-tuned desde ImageNet                                                            │
│  - Interpretabilidad: Grad-CAM en layer4[-1]                                                                    │
│  - Tiempo de inferencia: ~50ms por imagen (GPU)                                                                 │
│  - Error: 1/107 (una nanoparticula clasificada como nanohilo)                                                   │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Cientifico Senior en Vision Artificial y Nanomateriales                                                 │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  Informe Técnico: Viabilidad del Clasificador SEM ResNet-18 como Producto Comercial                             │
│                                                                                                                 │
│  El clasificador SEM basado en ResNet-18 demuestra una viabilidad técnica prometedora como producto comercial,  │
│  evidenciado por métricas de rendimiento excepcionales. Con un *Accuracy del 99.07%*, un *F1-Score de 0.9903*   │
│  y un *AUC-ROC de 0.9943* en la clasificación de nanopartículas (0D) vs. nanowires (1D), el modelo supera las   │
│  expectativas para una tarea binaria. El error de solo 1/107 imágenes es notable.                               │
│                                                                                                                 │
│  **1. Competitividad frente a soluciones existentes:**                                                          │
│  Frente a alternativas comerciales como *Thermo Fisher Avizo* o *MIPAR*, que ofrecen soluciones de análisis de  │
│  imágenes más generales y a menudo requieren configuraciones manuales extensas para tareas específicas,         │
│  nuestro modelo destaca por su alta precisión y automatización en una clasificación crítica de nanomateriales.  │
│  Si bien Avizo y MIPAR son plataformas robustas para análisis 3D y segmentación compleja, la especialización y  │
│  el rendimiento del ResNet-18 en la clasificación 0D/1D lo posicionan como una herramienta complementaria o     │
│  incluso superior para esta tarea específica, ofreciendo una solución "plug-and-play" con un rendimiento        │
│  cuantificable y superior a la intervención manual. La interpretabilidad mediante Grad-CAM añade un valor       │
│  significativo, ausente en muchas soluciones "caja negra".                                                      │
│                                                                                                                 │
│  **2. Limitaciones técnicas y mitigación:**                                                                     │
│  La principal limitación actual es la **binaridad de la clasificación (0D vs 1D)**. Para mitigar esto, es       │
│  esencial expandir el dataset para incluir más clases de nanomateriales (e.g., 2D, 3D, aglomerados, defectos).  │
│  Otra limitación es la **dependencia del dataset NFFA-EUROPE SEM**, lo que podría limitar la generalización a   │
│  imágenes SEM de otras fuentes o condiciones. Esto se mitigará con la curación de datasets más diversos y la    │
│  aplicación de técnicas de aumento de datos.                                                                    │
│                                                                                                                 │
│  **3. Roadmap de mejoras:**                                                                                     │
│  *   **Fase 1 (Corto Plazo - 3 meses):**                                                                        │
│      *   **Multi-clase:** Expandir el modelo para clasificar 3-5 clases adicionales de nanomateriales (e.g.,    │
│  2D Nanosheets, Nanotubes, Quantum Dots).                                                                       │
│      *   **Aumento de datos:** Implementar técnicas avanzadas de aumento de datos para mejorar la robustez y    │
│  generalización del modelo.                            

[CrewAIEventsBus] Warning: Event pairing mismatch. 'agent_execution_completed' closed 'llm_call_started' (expected 
'agent_execution_started')

[CrewAIEventsBus] Warning: Event pairing mismatch. 'task_completed' closed 'agent_execution_started' (expected 
'task_started')

╭────────────────────────────────────────────── 📋 Task Completion ───────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: Evalua la viabilidad tecnica del clasificador SEM ResNet-18 como producto comercial. Usa la tool         │
│  sem_model_metrics para obtener las metricas reales del modelo. Analiza: (1) Competitividad frente a            │
│  soluciones existentes, (2) Limitaciones tecnicas y como mitigarlas, (3) Roadmap de mejoras (multi-clase,       │
│  segmentacion, etc.), (4) Requisitos de infraestructura (GPU, cloud).                                           │
│  Agent: Cientifico Senior en Vision Artificial y Nanomateriales                                                 │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── 📋 Task Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Started                                                                                                   │
│  Name: Realiza un analisis de mercado para un SaaS de clasificacion automatica de micrografias SEM. Incluye:    │
│  (1) TAM del mercado de software de caracterizacion de materiales, (2) Segmento objetivo (universidades,        │
│  centros de I+D, industria), (3) Modelo de pricing (por imagen, suscripcion mensual, enterprise), (4)           │
│  Estimacion de costos operativos (cloud GPU, desarrollo, soporte).                                              │
│  ID: e813061a-ca9d-423c-bac0-0cac2ef4ecd1                                                                       │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Analista de Mercado en Tecnologia Deep Tech                                                             │
│                                                                                                                 │
│  Task: Realiza un analisis de mercado para un SaaS de clasificacion automatica de micrografias SEM. Incluye:    │
│  (1) TAM del mercado de software de caracterizacion de materiales, (2) Segmento objetivo (universidades,        │
│  centros de I+D, industria), (3) Modelo de pricing (por imagen, suscripcion mensual, enterprise), (4)           │
│  Estimacion de costos operativos (cloud GPU, desarrollo, soporte).                                              │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Analista de Mercado en Tecnologia Deep Tech                                                             │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  ## Análisis de Mercado: SaaS de Clasificación Automática de Micrografías SEM                                   │
│                                                                                                                 │
│  El mercado de software de caracterización de materiales, donde se inserta un SaaS de clasificación automática  │
│  de micrografías SEM, es un nicho de alto valor impulsado por la I+D en ciencia de materiales, nanotecnología   │
│  y control de calidad industrial.                                                                               │
│                                                                                                                 │
│  **1. TAM del Mercado de Software de Caracterización de Materiales:**                                           │
│  El mercado global de software de caracterización de materiales se estima en **$1.5 - $2.0 mil millones en      │
│  2023**, con una tasa de crecimiento anual compuesta (CAGR) del 8-10% hasta 2028. Este TAM incluye soluciones   │
│  de análisis de imagen (como Avizo, MIPAR), software de control de instrumentos (Thermo Fisher, Bruker,         │
│  ZEISS), y plataformas de gestión de datos. Nuestro producto, al ser una solución especializada de análisis de  │
│  imagen basada en IA, se enfoca en un subsegmento de este mercado.                                              │
│                                                                                                                 │
│  **2. Segmento Objetivo (SAM/SOM):**                                                                            │
│  *   **SAM (Serviceable Available Market):** Nos dirigimos a laboratorios de investigación (universidades,      │
│  centros de I+D) y departamentos de I+D en la industria (farmacéutica, automotriz, electrónica, aeroespacial)   │
│  que utilizan microscopía SEM para caracterización de nanomateriales. Estimamos este SAM en **$150 - $250       │
│  millones anuales**, considerando el gasto en software de análisis de imagen y servicios de caracterización.    │
│  *   **SOM (Serviceable Obtainable Market):** Con una solución inicial binaria (0D vs 1D) y un roadmap claro,   │
│  un SOM conservador para los primeros 3 años sería del **0.5% - 1.5% del SAM**, lo que representa **$0.75 -     │
│  $3.75 millones anuales**. Este SOM crecerá a medida que se expandan las capacidades multi-clase y de           │
│  segmentación.                                                                                                  │
│                                                                                                                 │
│  **3. Modelo de Pricing:**                                                                                      │
│  Proponemos un modelo híbrido que combina suscripción y pago por uso, con una opción Enterprise para grandes    │
│  consumidores.                                                                                                  │
│                                                                                                                 │
│  | Tier / Característica | Básico (Investigador) | Pro (Laboratorio) | Enterprise (Corporativo) |               │
│  | :-------------------- | :-------------------- | :---------------- | :---------------------- |                │
│  | **Precio Mensual**    | $99                   | $499

╭────────────────────────────────────────────── 📋 Task Completion ───────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: Realiza un analisis de mercado para un SaaS de clasificacion automatica de micrografias SEM. Incluye:    │
│  (1) TAM del mercado de software de caracterizacion de materiales, (2) Segmento objetivo (universidades,        │
│  centros de I+D, industria), (3) Modelo de pricing (por imagen, suscripcion mensual, enterprise), (4)           │
│  Estimacion de costos operativos (cloud GPU, desarrollo, soporte).                                              │
│  Agent: Analista de Mercado en Tecnologia Deep Tech                                                             │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── 📋 Task Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Started                                                                                                   │
│  Name: Analiza los requisitos legales para comercializar un software de clasificacion de nanomateriales a       │
│  nivel global. Cubre: (1) Regulacion de nanomateriales (REACH, TSCA), (2) Certificaciones de software           │
│  analitico (ISO 17025), (3) Proteccion de datos y propiedad intelectual, (4) Diferencias entre mercados US, EU  │
│  y Asia.                                                                                                        │
│  ID: fb668403-edbf-4b77-be03-4c6b3b6fd46f                                                                       │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Regulacion de Nanotecnologia y Software Medico                                          │
│                                                                                                                 │
│  Task: Analiza los requisitos legales para comercializar un software de clasificacion de nanomateriales a       │
│  nivel global. Cubre: (1) Regulacion de nanomateriales (REACH, TSCA), (2) Certificaciones de software           │
│  analitico (ISO 17025), (3) Proteccion de datos y propiedad intelectual, (4) Diferencias entre mercados US, EU  │
│  y Asia.                                                                                                        │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Especialista en Regulacion de Nanotecnologia y Software Medico                                          │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  El software de clasificación de nanomateriales basado en ResNet-18, con su alta precisión, se posiciona como   │
│  una herramienta valiosa. Sin embargo, su comercialización global requiere una navegación cuidadosa del         │
│  panorama regulatorio.                                                                                          │
│                                                                                                                 │
│  **Análisis Regulatorio:**                                                                                      │
│                                                                                                                 │
│  1.  **Regulación de Nanomateriales (REACH, TSCA):**                                                            │
│      *   **EU (REACH):** El software en sí no está directamente regulado por REACH, ya que REACH se aplica a    │
│  sustancias y mezclas. No obstante, si el software se utiliza para generar datos que se presentarán a la ECHA   │
│  para el registro de nanomateriales (como parte de un expediente REACH), la fiabilidad y validación de esos     │
│  datos son cruciales. La ECHA ha publicado guías sobre la caracterización de nanomateriales, y el software      │
│  debería ser capaz de generar resultados que cumplan con estas guías.                                           │
│      *   **US (TSCA):** Similar a REACH, TSCA regula las sustancias químicas. La EPA ha emitido requisitos de   │
│  notificación para ciertos nanomateriales. Si el software se utiliza para caracterizar nanomateriales que       │
│  requieren notificación bajo TSCA, la precisión y la trazabilidad de los resultados son fundamentales para el   │
│  cumplimiento.                                                                                                  │
│                                                                                                                 │
│  2.  **Certificaciones de Software Analítico (ISO 17025):**                                                     │
│      *   **ISO 17025:** Esta norma es para la competencia de laboratorios de ensayo y calibración. Si el        │
│  software se comercializa para ser utilizado en laboratorios acreditados bajo ISO 17025, el software debe ser   │
│  validado y sus resultados deben ser trazables y fiables. Aunque el software en sí no se "certifica" bajo ISO   │
│  17025, el laboratorio que lo utiliza debe demostrar que el software es adecuado para su propósito, está        │
│  validado y sus resultados son confiables. Esto implica la necesidad de documentación exhaustiva del software,  │
│  pruebas de validación, control de versiones y gestión de cambios.                                              │
│      *   **21 CFR Part 11 (US FDA):** Si el software se utiliza en entornos regulados por la FDA (ej. para      │
│  caracterizar nanomateriales en productos farmacéuticos o dispositivos médicos), el software debe cumplir con   │
│  los requisitos de registros electrónicos y firmas electrónicas. Esto implica funcionalidades de auditoría,     │
│  seguridad, integridad de datos y trazabilidad.                                                                 │
│                                                                                                                 │
│  3.  **Protección de Datos y Propiedad Intelectual:**  

╭────────────────────────────────────────────── 📋 Task Completion ───────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: Analiza los requisitos legales para comercializar un software de clasificacion de nanomateriales a       │
│  nivel global. Cubre: (1) Regulacion de nanomateriales (REACH, TSCA), (2) Certificaciones de software           │
│  analitico (ISO 17025), (3) Proteccion de datos y propiedad intelectual, (4) Diferencias entre mercados US, EU  │
│  y Asia.                                                                                                        │
│  Agent: Especialista en Regulacion de Nanotecnologia y Software Medico                                          │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── 📋 Task Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Started                                                                                                   │
│  Name: Integra los informes del cientifico, economista y regulatorio en un executive summary de exactamente 1   │
│  pagina (400-500 palabras) para inversores. Estructura: Problema → Solucion → Mercado → Modelo de Negocio →     │
│  Tecnologia → Regulatorio → Ask (inversion necesaria).                                                          │
│  ID: f416e7e1-13bc-4e69-89e5-ba2fcbf027b1                                                                       │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭─────────────────────────────────────────────── 🤖 Agent Started ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Redactor de Executive Summaries para Inversores                                                         │
│                                                                                                                 │
│  Task: Integra los informes del cientifico, economista y regulatorio en un executive summary de exactamente 1   │
│  pagina (400-500 palabras) para inversores. Estructura: Problema → Solucion → Mercado → Modelo de Negocio →     │
│  Tecnologia → Regulatorio → Ask (inversion necesaria).                                                          │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────────────────────── ✅ Agent Final Answer ─────────────────────────────────────────────╮
│                                                                                                                 │
│  Agent: Redactor de Executive Summaries para Inversores                                                         │
│                                                                                                                 │
│  Final Answer:                                                                                                  │
│  ## Executive Summary: Clasificador SEM de Nanomateriales                                                       │
│                                                                                                                 │
│  ### Problema                                                                                                   │
│  La caracterización de nanomateriales mediante microscopía electrónica de barrido (SEM) es un cuello de         │
│  botella crítico en I+D y control de calidad. Los métodos actuales son manuales, lentos y propensos a errores,  │
│  limitando la escalabilidad y la reproducibilidad en industrias como la farmacéutica y electrónica. La falta    │
│  de automatización precisa retrasa el desarrollo de productos y la validación de procesos.                      │
│                                                                                                                 │
│  ### Solución                                                                                                   │
│  Hemos desarrollado un clasificador de imágenes SEM basado en ResNet-18 que automatiza la identificación de     │
│  nanomateriales con una precisión del 99.07% y un F1-Score de 0.9903. Esta solución SaaS ofrece una             │
│  clasificación "plug-and-play" de nanopartículas (0D) vs. nanowires (1D) en ~50ms por imagen, superando la      │
│  velocidad y fiabilidad de las alternativas manuales y software genérico. La interpretabilidad vía Grad-CAM     │
│  añade transparencia a la toma de decisiones.                                                                   │
│                                                                                                                 │
│  ### Mercado                                                                                                    │
│  El mercado global de software de caracterización de materiales es de $1.5-2.0 mil millones, creciendo al       │
│  8-10% CAGR. Nuestro SAM (Serviceable Available Market) inicial, enfocado en laboratorios de I+D y              │
│  departamentos industriales, asciende a $150-250 millones anuales. Proyectamos un SOM (Serviceable Obtainable   │
│  Market) conservador de $0.75-3.75 millones en los primeros 3 años, escalable con la expansión de               │
│  funcionalidades.                                                                                               │
│                                                                                                                 │
│  ### Modelo de Negocio                                                                                          │
│  Operamos bajo un modelo SaaS híbrido de suscripción y pago por uso, con tiers Básico ($99/mes), Pro            │
│  ($499/mes) y Enterprise (personalizado). Esto permite flexibilidad para investigadores individuales y grandes  │
│  corporaciones. Con costos operativos mensuales de $21.6k-$35.5k, proyectamos ingresos anuales de $120k en el   │
│  Año 1, $360k en el Año 2 y $720k en el Año 3, impulsados por la expansión de clientes y funcionalidades.       │
│                                                                                                                 │
│  ### Tecnología                                                                                                 │
│  Nuestro clasificador ResNet-18, entrenado con el datas

╭────────────────────────────────────────────── 📋 Task Completion ───────────────────────────────────────────────╮
│                                                                                                                 │
│  Task Completed                                                                                                 │
│  Name: Integra los informes del cientifico, economista y regulatorio en un executive summary de exactamente 1   │
│  pagina (400-500 palabras) para inversores. Estructura: Problema → Solucion → Mercado → Modelo de Negocio →     │
│  Tecnologia → Regulatorio → Ask (inversion necesaria).                                                          │
│  Agent: Redactor de Executive Summaries para Inversores                                                         │
│                                                                                                                 │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

[CrewAIEventsBus] Warning: Event pairing mismatch. 'crew_kickoff_completed' closed 'task_started' (expected 
'crew_kickoff_started')

╭──────────────────────────────────────────────── Crew Completion ────────────────────────────────────────────────╮
│                                                                                                                 │
│  Crew Execution Completed                                                                                       │
│  Name: crew                                                                                                     │
│  ID: c43cd0dd-ee4b-4e67-b42e-be27af1b89da                                                                       │
│  Final Output: ## Executive Summary: Clasificador SEM de Nanomateriales                                         │
│                                                                                                                 │
│  ### Problema                                                                                                   │
│  La caracterización de nanomateriales mediante microscopía electrónica de barrido (SEM) es un cuello de         │
│  botella crítico en I+D y control de calidad. Los métodos actuales son manuales, lentos y propensos a errores,  │
│  limitando la escalabilidad y la reproducibilidad en industrias como la farmacéutica y electrónica. La falta    │
│  de automatización precisa retrasa el desarrollo de productos y la validación de procesos.                      │
│                                                                                                                 │
│  ### Solución                                                                                                   │
│  Hemos desarrollado un clasificador de imágenes SEM basado en ResNet-18 que automatiza la identificación de     │
│  nanomateriales con una precisión del 99.07% y un F1-Score de 0.9903. Esta solución SaaS ofrece una             │
│  clasificación "plug-and-play" de nanopartículas (0D) vs. nanowires (1D) en ~50ms por imagen, superando la      │
│  velocidad y fiabilidad de las alternativas manuales y software genérico. La interpretabilidad vía Grad-CAM     │
│  añade transparencia a la toma de decisiones.                                                                   │
│                                                                                                                 │
│  ### Mercado                                                                                                    │
│  El mercado global de software de caracterización de materiales es de $1.5-2.0 mil millones, creciendo al       │
│  8-10% CAGR. Nuestro SAM (Serviceable Available Market) inicial, enfocado en laboratorios de I+D y              │
│  departamentos industriales, asciende a $150-250 millones anuales. Proyectamos un SOM (Serviceable Obtainable   │
│  Market) conservador de $0.75-3.75 millones en los primeros 3 años, escalable con la expansión de               │
│  funcionalidades.                                                                                               │
│                                                                                                                 │
│  ### Modelo de Negocio                                                                                          │
│  Operamos bajo un modelo SaaS híbrido de suscripción y pago por uso, con tiers Básico ($99/mes), Pro            │
│  ($499/mes) y Enterprise (personalizado). Esto permite flexibilidad para investigadores individuales y grandes  │
│  corporaciones. Con costos operativos mensuales de $21.6k-$35.5k, proyectamos ingresos anuales de $120k en el   │
│  Año 1, $360k en el Año 2 y $720k en el Año 3, impulsados por la expansión de clientes y funcionalidades.       │
│                                                                                                                 │
│  ### Tecnología                                                                                                 │
│  Nuestro clasificador ResNet-18, entrenado con el data


EXECUTIVE SUMMARY FINAL:
## Executive Summary: Clasificador SEM de Nanomateriales

### Problema
La caracterización de nanomateriales mediante microscopía electrónica de barrido (SEM) es un cuello de botella crítico en I+D y control de calidad. Los métodos actuales son manuales, lentos y propensos a errores, limitando la escalabilidad y la reproducibilidad en industrias como la farmacéutica y electrónica. La falta de automatización precisa retrasa el desarrollo de productos y la validación de procesos.

### Solución
Hemos desarrollado un clasificador de imágenes SEM basado en ResNet-18 que automatiza la identificación de nanomateriales con una precisión del 99.07% y un F1-Score de 0.9903. Esta solución SaaS ofrece una clasificación "plug-and-play" de nanopartículas (0D) vs. nanowires (1D) en ~50ms por imagen, superando la velocidad y fiabilidad de las alternativas manuales y software genérico. La interpretabilidad vía Grad-CAM añade transparencia a la toma de decisiones.

### Mercado
E

╭──────────────────────────────────────────────── Tracing Status ─────────────────────────────────────────────────╮
│                                                                                                                 │
│  Info: Tracing is disabled.                                                                                     │
│                                                                                                                 │
│  To enable tracing, do any one of these:                                                                        │
│  • Set tracing=True in your Crew/Flow code                                                                      │
│  • Set CREWAI_TRACING_ENABLED=true in your project's .env file                                                  │
│  • Run: crewai traces enable                                                                                    │
│                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

### Evaluación con Output Scorer

Usamos `output_scorer` con criterios personalizados para el dominio de negocio,
buscando un score > 0.85.

In [6]:
from langchain_openai import ChatOpenAI
llm_langchain = ChatOpenAI(
    base_url='https://openrouter.ai/api/v1',
    api_key=os.environ.get('OPENROUTER_API_KEY'),
    model='google/gemini-2.5-flash',
    temperature=0,
    default_headers={
        'HTTP-Referer': 'https://github.com/antigravity-nano',
        'X-Title': 'SEM Business Plan Scorer',
    },
)

# ============================================================
# EVALUACIÓN CON OUTPUT_SCORER
# ============================================================
import sys
from pathlib import Path

# Asegurar acceso a external_skills
_root = Path.cwd()
for _ in range(6):
    if (_root / "external_skills").exists():
        if str(_root) not in sys.path:
            sys.path.insert(0, str(_root))
        break
    _root = _root.parent

from external_skills.evaluation.output_scorer import score_with_llm

criterios_negocio = {
    "viabilidad_tecnica": 0.20,
    "analisis_mercado": 0.20,
    "compliance_regulatorio": 0.15,
    "datos_cuantitativos": 0.20,
    "claridad_ejecutiva": 0.15,
    "accionabilidad": 0.10,
}

evaluacion = score_with_llm(
    output=resultado_negocio.raw,
    task_description=(
        "Executive summary de 1 pagina para inversores sobre la comercializacion "
        "de un clasificador SEM basado en ResNet-18 como servicio SaaS."
    ),
    criteria=criterios_negocio,
    llm=llm_langchain,
)

print("\n" + "=" * 60)
print("EVALUACIÓN DEL PLAN DE NEGOCIO")
print("=" * 60)
pct = evaluacion.score / evaluacion.max_score
grade = (
    "EXCELENTE" if pct > 0.85 else
    "BUENO" if pct > 0.70 else
    "ACEPTABLE" if pct > 0.55 else
    "INSUFICIENTE"
)
print(f"Score: {evaluacion.score:.2f}/{evaluacion.max_score} ({grade})")
print(f"Objetivo: > 0.85 → {'CUMPLIDO' if pct > 0.85 else 'PENDIENTE DE AJUSTE'}")
print()
print("Breakdown por criterio:")
for dim, val in evaluacion.breakdown.items():
    bar = "█" * int(val * 10) + "░" * (10 - int(val * 10))
    print(f"  {dim:<25} {bar} {val:.2f}")
print(f"\nFeedback:\n{evaluacion.feedback}")


EVALUACIÓN DEL PLAN DE NEGOCIO
Score: 0.83/1.0 (BUENO)
Objetivo: > 0.85 → PENDIENTE DE AJUSTE

Breakdown por criterio:
  viabilidad_tecnica        █████████░ 0.90
  analisis_mercado          ████████░░ 0.80
  compliance_regulatorio    ███████░░░ 0.70
  datos_cuantitativos       ████████░░ 0.85
  claridad_ejecutiva        █████████░ 0.90
  accionabilidad            ████████░░ 0.80

Feedback:
Evaluación LLM de 'Executive summary de 1 pagina para inversores sobre la comer': viabilidad_tecnica: 90%, analisis_mercado: 80%, compliance_regulatorio: 70%, datos_cuantitativos: 85%, claridad_ejecutiva: 90%, accionabilidad: 80%. Score total: 83%.


### Resumen del Ejercicio

| Requisito | Implementación | Estado |
|-----------|---------------|--------|
| Agente Científico con tools | `cientifico` + `SEMModelMetricsTool` (métricas reales ResNet-18) | ✅ |
| Agente Economista | `economista` con análisis TAM/SAM/SOM y pricing | ✅ |
| Agente Regulatorio | `regulatorio` con REACH, TSCA, ISO 17025 | ✅ |
| Redactor Ejecutivo | `redactor_ejecutivo` integrando los 3 informes en 1 página | ✅ |
| Output Scorer con criterios de negocio | 6 criterios ponderados, objetivo score > 0.85 | ✅ |
| Backstories diferenciadas | Cada agente tiene expertise específica y cuantificada | ✅ |

**Contexto del Proyecto Final**: El plan de negocio evalúa la comercialización del clasificador
SEM ResNet-18 (Accuracy 99.07%, AUC-ROC 0.9943) como servicio SaaS para laboratorios de nanotecnología.